repository:
  internal: true
  has_issues: false
  has_projects: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  topics: malty, innersource, design, dsm

labels:
  - name: bug
    color: EE0701
    description: An issue with the system.

  - name: dependencies
    color: 0366D6
    description: Pull requests that update a dependency file or issues with a dependency.

  - name: documentation
    color: 0075CA
    description: Improvements or additions to documentation

  - name: duplicate
    color: CCCCCC
    description: A duplicated issue or pull request

  - name: enhancement
    color: A2EEEF
    description: New feature or request

  - name: good first issue
    color: 7057FF
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: invalid
    color: E4E669
    description: This doesn't seem right

  - name: question
    color: CC317C
    description: Further information is requested

  - name: wontfix
    color: FFFFFF
    description: This will not be worked on

  - name: react18issue
    color: BB0000
    description: Issue related to React v18 Typescript types issue

teams:
  - name: malty-maintainers
    permission: admin

  - name: malty-contributors
    permission: write

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      required_conversation_resolution: true
      restrictions:
        apps: []
        users: []
        teams: [malty-maintainers]

  - name: feature/*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: [malty-contributors]

  - name: maintenance/*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: [malty-maintainers]
