name: Access Request
description: Please choose this category if you need access to any platform or application available on the Design Systems, Confluence or JIRA
title: 'access-request: '
labels: [Access]
assignees: [galmeida12, MartimMatosCB, vicenteopaso, marianacarlsberg]
body:
  - type: input
    attributes:
      label: Summary
      description: Please tell us which access do you need
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Please tell us why do you need access to this

  - type: input
    attributes:
      label: Github handle
      description: Please enter your GitHub handle, for both GitHub and Bit.dev
    validations:
      required: true

  - type: input
    attributes:
      label: SAM Account Name
      description: Please enter your login email address, as you use it to login to Teams, etc.
      placeholder: PTLASFIR@carlsberggroup.com
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Application
      description: Please tell us to which application(s) you need access
      options:
        - label: Jira
        - label: Confluence
        - label: Bit.dev
        - label: Figma
        - label: Github

  - type: dropdown
    attributes:
      label: Priority
      description: Tell us what's the priority that this request have to you
      options:
        - Blocker
        - Highest
        - High
        - Medium
        - Low
        - Lowest
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Team
      description: The team which the ticket reporter belongs
      options:
        - Cadi
        - CS WE
        - CS+
        - Lean Signup
        - Ottilia
        - InnerSource Community
        - OutSource Community
    validations:
      required: true
