name: Bug
description: Issue with a Component and/or Feature? Please tell us what are the problems that you are experiencing
title: 'bug: '
labels: [Bug, Issue]
assignees: [galmeida12, marianacarlsberg, MartimMatosCB, vicenteopaso]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the title above with the appropriate summary of the issue

  - type: textarea
    attributes:
      label: Description
      description: Please explain us, in a succinct way, what's the problem that you're facing. You can also attach files
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: Tell us what's the priority that this bug have to you
      options:
        - Blocker
        - Higher
        - High
        - Medium
        - Low
        - Lowest
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Team
      description: The team which the ticket reporter belongs
      options:
        - Cadi
        - CS WE
        - CS+
        - Lean Signup
        - Ottilia
        - InnerSource Community
        - OpenSource Community
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Component
      description: Please tell us the affected Component
      options:
        - Alert
        - Button
        - Checkbox
        - Chip
        - Colors
        - Floater
        - Headline
        - Icon
        - Icon Wrapper
        - Image
        - Input
        - Label
        - Link
        - Overlay
        - Padded Container
        - Pagination
        - Pill
        - Progress Bar
        - Progress Spinner
        - Radio
        - Rating
        - Stepper
        - Select
        - Table
        - Text
        - Text Area
        - Tooltip
        - Toggle
        - Theme Provider
        - Others
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Device
      description: Please specify in which device the problem occur
      options:
        - label: Mobile
        - label: Tablet
        - label: Laptop
        - label: Desktop
    validations:
      required: true
