name: New Request
description: Submit your component and/or feature request here
title: 'new-request: '
labels: [enhancement]
assignees: [galmeida12, marianacarlsberg, MartimMatosCB, vicenteopaso]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the title above

  - type: textarea
    attributes:
      label: Description
      description: Please describe the request. You can also attach files
    validations:
      required: true

  - type: textarea
    attributes:
      label: Purpose & Justification
      description: Describe why for what you need this request
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Application
      description: Please tell us to which application(s) you need access
      options:
        - label: Jira
        - label: Confluence
        - label: Bit.dev
        - label: Figma
        - label: Github

  - type: dropdown
    attributes:
      label: Priority
      description: Tell us what's the priority that this request have to you
      options:
        - Blocker
        - Higher
        - High
        - Medium
        - Low
        - Lowest
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Team
      description: The team which the ticket reporter belongs
      options:
        - Cadi
        - CS WE
        - CS+
        - Lean Signup
        - Ottilia
        - InnerSource Community
        - OpenSource Community
    validations:
      required: true
