name: Other
description: Other requests that do not fit any of the previous options
title: 'other: '
labels: [other, request]
assignees: [galmeida12, marianacarlsberg, MartimMatosCB, vicenteopaso]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the title above with the appropriate summary of the issue

  - type: textarea
    attributes:
      label: Description
      description: Please give us as much information as possible. You can also attach files
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Team
      description: The team which the ticket reporter belongs
      options:
        - Cadi
        - CS WE
        - CS+
        - Lean Signup
        - Ottilia
        - InnerSource Community
        - OpenSource Community
    validations:
      required: true
