name: Approval

on:
  pull_request:
    branches: [main]

jobs:
  require_approval:
    name: Require Approval
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'ci/')
    steps:
      - id: token
        name: Authenticate
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.CARLSBERG_SECURITY_APP_ID }}
          private_key: "${{ secrets.CARLSBERG_SECURITY_APP_PRIVATE_KEY }}"

      - name: Check Reviewers
        run: |
          approved=0
          team="malty-designers"
          reviews=$(gh api "/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | jq -cr)
          reviews=$(echo "$reviews" | jq -cr '.[] | (.user.login + " " + .state)')

          for review in "$reviews"; do
              user="$(echo $review | awk '{print $1}')"
              state="$(echo $review | awk '{print $2}')"

              gh api "/orgs/${{ github.repository_owner }}/teams/$team/memberships/$user" &>/dev/null
              resp_code=$?

              printf "checking %s: %s" "$user" "$state"

              if [[ $resp_code -eq 0 && "$state" == "APPROVED" ]]; then
                  echo " - belongs to $team\n"
                  approved=1
                  break
              else
                  echo " - doesn't belong to $team\n"
              fi
          done

          if [[ $approved -eq 1 ]]; then
              # Create successful check
              echo "approved!"
          else
              # Create failure check
              echo "not approved! :("
          fi
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
