name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests-run:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm

      - name: Install latest Bit version
        run: |
          export PATH=${{ env.PATH }}
          bvm install

      - name: Add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: |
          echo "Adding bit.dev to npm registry"
          export PATH=${{ env.PATH }}
          npm config set @bit:registry https://node.bit.dev
          npm config set @carlsberggroup:registry=https://node.bit.dev
          npm config set @teambit:registry=https://node.bit.dev
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${BIT_TOKEN}
          echo "Completed adding bit.dev to npm registry"

      - name: Bit Deps Install & Compile
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export PATH=${{ env.PATH }}
          yarn cache clean --force
          bit clear-cache
          bit install
          bit compile
        shell: bash

      - name: Run Unit Tests
        run: |
          yarn test:ci
        shell: bash
