name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests-run:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Register remote scopes
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set @bit:registry https://node.bit.cloud
          npm config set @carlsberggroup:registry=https://node.bit.cloud
          npm config set @teambit:registry=https://node.bit.cloud
          echo "Completed adding bit.dev to npm registry"
        shell: bash

      - name: Install Bit
        run: |
          npx @teambit/bvm install
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies (Bit CLI)
        run: |
          export PATH=${{ env.PATH }}
          yarn wipe
          bit install
          bit compile
        shell: bash

      - name: Run Unit Tests
        run: |
          yarn test:ci
        shell: bash
