name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-tests:
    name: 'Env. Preparation'
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: init bit.dev
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set @bit:registry https://node.bit.dev
          npm config set @carlsberggroup:registry=https://node.bit.dev
          npm config set @teambit:registry=https://node.bit.dev
          npm config set //node.bit.dev/:_authToken ${BIT_TOKEN}
          echo "Completed adding bit.dev to npm registry"
        env:
          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

      - name: Install Bit CLI
        run: |
          npx @teambit/bvm install
          export PATH=$HOME/bin:$PATH
          bit config set user.token ${{ secrets.BIT_TOKEN }}
        shell: bash

  deps-install:
    name: 'Install Dependencies'
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - name: Install Components
        run: bit install
        shell: bash

      - name: Compile components
        run: bit compile
        shell: bash

  tests-run:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - name: Unit Tests
        run: yarn test
        shell: bash
