name: Version Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Set npm registry and authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stash .npmrc changes
        run: git stash push --keep-index --message "Stashing .npmrc changes"
        continue-on-error: true

      - name: Install dependecies
        run: |
          if [ -e yarn.lock ]; then
          yarn install
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Run Lerna Version
        run: npx lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unstash .npmrc changes
        if: failure()
        run: git stash pop
