name: Visual testing

on:
  workflow_run:
    workflows: ['AWS Amplify Console Web Preview']
    types:
      - completed
  workflow_dispatch:
  repository_dispatch:
    types: [run_visual_testing]
  pull_request:
    branches: [main]

jobs:
  visual-testing:
    runs-on: ubuntu-latest

    env:
      AMPLIFY_LINK: https://pr-${{ github.event.number }}.d3acoh2jwy8aw9.amplifyapp.com
      CYPRESS_IMAGE: cypress/included:cypress-13.6.4-node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1

    # container: cypress/included:cypress-13.6.4-node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1
    steps:
      - uses: actions/checkout@v3

      #- name: Run visual testing
      #  run: cypress run --browser chrome --config viewportWidth=1024,viewportHeight=768

      - name: Run Visual Testing
        run: docker run -it -v $PWD:/e2e -w /e2e -e BASE_URL=${{ env.AMPLIFY_LINK }} ${{ env.CYPRESS_IMAGE }} --browser chrome --config viewportWidth=1024,viewportHeight=768
