name: Upload to S3

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "AWS_ACCESS_KEY_ID ${{ secrets.AWS_ACCESS_KEY_ID }}"
      - run: echo "AWS_S3_BUCKET ${{ secrets.AWS_S3_BUCKET }}"
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: 'docs'
